name: usecase
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Internal Packages
  entity:
    path: ../entity
  repository:
    path: ../repository
  get_it: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^3.0.0
